### ISSUE TITLE
release a version with the latest fit.js?

### ISSUE THREAD

**Issue by mattgalvin** [pierremtb/easy-fit#11]
Any chance of a version release to the registry that has the latest fit.js file? The mileage conversion in npm is way off but it's been fixed in source, just not pushed to the registry.

**Comment by pierremtb** [comment]
Oh well I forgot to do it. Let me fix that tonight.

**Comment by mattgalvin** [comment]
No worries, thanks!

**Comment by pierremtb** [comment]
I updated the npm module.
So sorry for being that late, I totally forgot.
