### ISSUE TITLE
Strange record data when importing a fit file from movescount

### ISSUE THREAD

**Issue by jimmykane** [pierremtb/easy-fit#14]
Hi there, 

I get this strange data when importing a .fit file from movescount. Take a look:
<img width="551" alt="screen shot 2017-06-24 at 14 20 06" src="https://user-images.githubusercontent.com/1268723/27508566-6419ebbc-58e8-11e7-9330-dcdcbaa7aa94.png">

As you can see all the points that do have a lat long have out of space values. 

Do you have any clue for this ?

**Comment by pierremtb** [comment]
Hi, sorry for the delay.

That's very strange. I've only tested the parser against .FIT files that came from Garmin devices. Does this occur with all your files ?

**Comment by jimmykane** [comment]
Not all. Let me pass you one from Stryd . I think this might happen due to not having GPS data? 
Not a big prio but it would be great if you could spend a little time cause I am really lost with binary data. 


[1497535008-GIR.fit.zip](https://github.com/pierremtb/easy-fit/files/1152004/1497535008-GIR.fit.zip)

**Comment by jimmykane** [comment]
Btw I fixed it for the previous example. It's ok. They just had strange values. 

Still though that file gets parsed empty.
