### ISSUE TITLE
There is something wrong with NPM package version

### ISSUE THREAD

**Issue by jimmykane** [pierremtb/easy-fit#21]
Hi, 
currently, the NPM offers version 0.0.7 

However, this commit is not included when using 0.0.7 

a4d6368248b842df7d25e743486c231777f1b590

What am I missing ?

**Comment by pierremtb** [comment]
That's indeed true. Let me fix this. Looks like I may have forgotten to run babel before pushing to the npm registry 😕

**Comment by jimmykane** [comment]
@pierremtb exactly. I was like with. I cloned the repo etc used npm with commitish ref but no luck. 
Then I realized that it's in the dist folder :-O

**Comment by jimmykane** [comment]
@pierremtb  thanks a ton btw

**Comment by pierremtb** [comment]
Should be fine now with 0.0.8. Thanks for reporting @jimmykane
