### ISSUE TITLE
Records incomplete when trying to parse a fit file from a Wahoo GPS

### ISSUE THREAD

**Issue by jgeert1** [pierremtb/easy-fit#28]
I've tried to parse a fit file from a Wahoo GPS, but I always get 2 records in the resulting json while the file itself (verified in Basecamp) have thousands of track points in it.

Any idea what's wrong here?
I have no issues with the parsing of other fit files (from Garmin units), all of these are ok.
[Wahoo.zip](https://github.com/pierremtb/easy-fit/files/2876873/Wahoo.zip)

**Comment by jimmykane** [comment]
@jgeert1  you 2 wahoo files load just fine on 
https://quantified-self.io/user/dHz2Mbrea3Oht2E9y47uQGEP8f22/event/RIiCvcKOADz1QPPDTymq
https://quantified-self.io/user/dHz2Mbrea3Oht2E9y47uQGEP8f22/event/C41ROSaEPFr4TIfeKOCh 

Try to use my fork of this lib that I have patched those issues. 

check it at https://github.com/jimmykane/easy-fit

**Comment by jgeert1** [comment]
@jimmykane , I just tried it and it works fine :-)
Thanks.
