### ISSUE TITLE
How can i use it without node

### ISSUE THREAD

**Issue by khertan** [pierremtb/easy-fit#5]
How can i use it without node. I would like to use it in an angularjs application.
So require didn t exists. How to transpil it ?
Thanks

**Comment by pierremtb** [comment]
Closed with #4, thanks!

**Comment by gfmoore** [comment]
Hi, late to the show I guess,

I had a look at this, but browserify doesn't work with ES6 module import and export. I understand that I could transpile it to ES5 with babel (though I don't know how to do that). Just wondering if there was any other solution?

I suppose I could manually copy and paste the modules into the main js file, but that seems a bit counter-productive. (Though I'll probably have a go for now.)

Gordon
